### ISSUE TITLE
Update use of AstyanaxClient to perform NodeDiscovery

### ISSUE THREAD

**Issue by boneill42** [hmsonline/storm-cassandra#20]
In AsytanaxClient, we don't use the NodeDiscovery.  It should be a small change to use the NodeDiscovery to get high-availability, but needs to be tested.

.put(ASTYANAX_CONFIGURATION, new AstyanaxConfigurationImpl().setDiscoveryType(NodeDiscoveryType.NONE))

In general, we should think of some way to have this passed in the Storm configuration.

**Comment by ptgoetz** [comment]
Added in 0.4.0-rc1
