### ISSUE TITLE
Unable to run PersistentWordCount

### ISSUE THREAD

**Issue by rosepriya** [hmsonline/storm-cassandra#9]
Trying to run the following command still runs CassandraReachTopology instead of PersistentWordCount
mvn exec:java -Dexec.mainClass=backtype.storm.contrib.cassandra.example.PersistentWordCount

Is this because examples/pom.xml containing CassandraReachTopology in the exec:java plugin?

**Comment by ptgoetz** [comment]
Yes that was it. Fixed in master.

**Comment by rosepriya** [comment]
Thanks very much
